-- Legacy bootstrap reference only; the application does not execute this file automatically.
-- Current chat/FAQ runtime tables are public.chat_rooms, public.chat_messages,
-- public.faq_rooms, and public.faq_messages. Use sql/rename_core_tables_and_chat_status.sql.

CREATE TABLE IF NOT EXISTS users_kyj (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10000000) PRIMARY KEY
        CHECK (id BETWEEN 10000000 AND 99999999),
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'LocalUser'
        CHECK (role IN ('Admin', 'Developer', 'LocalUser')),
    lang_c CHAR(2) NOT NULL DEFAULT 'ko'
        CHECK (lang_c IN ('ko', 'en')),
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS manuals_kyj (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS manual_versions_kyj (
    id SERIAL PRIMARY KEY,
    manual_id INTEGER NOT NULL REFERENCES manuals_kyj(id) ON DELETE CASCADE,
    version_no INTEGER NOT NULL,
    file_name TEXT NOT NULL,
    file_url TEXT NOT NULL,
    index_step TEXT NOT NULL DEFAULT 'converting',
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (manual_id, version_no)
);

CREATE TABLE IF NOT EXISTS chat_rooms_kyj (
    room_id SERIAL PRIMARY KEY,
    room_user TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT '새 대화',
    summary TEXT NOT NULL DEFAULT '',
    last_summarized_message_id INTEGER NOT NULL DEFAULT 0,
    regis_date CHAR(8) NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'Asia/Seoul', 'YYYYMMDD'),
    regis_time CHAR(6) NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'Asia/Seoul', 'HH24MISS'),
    last_change_date CHAR(8) NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'Asia/Seoul', 'YYYYMMDD'),
    last_change_time CHAR(6) NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'Asia/Seoul', 'HH24MISS'),
    CHECK (regis_date ~ '^[0-9]{8}$'),
    CHECK (regis_time ~ '^[0-9]{6}$'),
    CHECK (last_change_date ~ '^[0-9]{8}$'),
    CHECK (last_change_time ~ '^[0-9]{6}$')
);

CREATE TABLE IF NOT EXISTS chat_messages_kyj (
    chat_id SERIAL PRIMARY KEY,
    room_id INTEGER NOT NULL REFERENCES chat_rooms_kyj(room_id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    text TEXT NOT NULL,
    type TEXT,
    options JSONB NOT NULL DEFAULT '[]',
    trace JSONB,
    sources JSONB NOT NULL DEFAULT '[]',
    regis_date CHAR(8) NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'Asia/Seoul', 'YYYYMMDD'),
    regis_time CHAR(6) NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'Asia/Seoul', 'HH24MISS'),
    CHECK (regis_date ~ '^[0-9]{8}$'),
    CHECK (regis_time ~ '^[0-9]{6}$')
);

CREATE INDEX IF NOT EXISTS chat_rooms_kyj_checkpoint_idx
    ON chat_rooms_kyj (room_user, last_summarized_message_id);

CREATE INDEX IF NOT EXISTS chat_messages_kyj_checkpoint_idx
    ON chat_messages_kyj (room_id, chat_id, regis_date, regis_time);

CREATE TABLE IF NOT EXISTS faq_history_kyj (
    id SERIAL PRIMARY KEY,
    source_room_id INTEGER REFERENCES chat_rooms_kyj(room_id) ON DELETE SET NULL,
    username TEXT NOT NULL,
    manual_id INTEGER REFERENCES manuals_kyj(id) ON DELETE SET NULL,
    conversation_summary TEXT NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    keywords TEXT[] NOT NULL DEFAULT '{}',
    faq_type TEXT NOT NULL DEFAULT 'conversation'
        CHECK (faq_type IN ('conversation', 'manual', 'screen_owner_change')),
    embedding vector(1536),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_by TEXT,
    approved_at TIMESTAMPTZ,
    rejected_by TEXT,
    rejected_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS faq_history_kyj_room_question_idx
    ON faq_history_kyj (source_room_id, question)
    WHERE source_room_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS faq_history_kyj_status_created_idx
    ON faq_history_kyj (status, created_at DESC);

CREATE INDEX IF NOT EXISTS faq_history_kyj_approved_embedding_idx
    ON faq_history_kyj USING hnsw (embedding vector_cosine_ops)
    WHERE status = 'approved' AND embedding IS NOT NULL;

CREATE TABLE IF NOT EXISTS manual_chunks_kyj (
    id SERIAL PRIMARY KEY,
    manual_id INTEGER NOT NULL REFERENCES manuals_kyj(id) ON DELETE CASCADE,
    version_id INTEGER NOT NULL REFERENCES manual_versions_kyj(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    section_title TEXT,
    keywords TEXT[] NOT NULL DEFAULT '{}',
    content TEXT NOT NULL,
    embedding vector(1536),
    content_tsv tsvector GENERATED ALWAYS AS (to_tsvector('simple', content)) STORED,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (version_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS manual_chunks_kyj_embedding_idx
    ON manual_chunks_kyj USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS manual_chunks_kyj_tsv_idx
    ON manual_chunks_kyj USING GIN (content_tsv);
CREATE INDEX IF NOT EXISTS manual_chunks_kyj_manual_id_idx
    ON manual_chunks_kyj (manual_id);

CREATE TABLE IF NOT EXISTS manual_upload_jobs_khs (
    id SERIAL PRIMARY KEY,
    manual_id INTEGER NOT NULL REFERENCES manuals(id) ON DELETE CASCADE,
    version_id INTEGER NOT NULL REFERENCES manual_versions(id) ON DELETE CASCADE,
    step TEXT NOT NULL DEFAULT 'converting',
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS source_documents (
    id SERIAL PRIMARY KEY,
    file_name TEXT NOT NULL,
    file_url TEXT NOT NULL,
    source_type TEXT NOT NULL,
    uploaded_by TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE manuals ADD COLUMN IF NOT EXISTS source_document_id INTEGER
    REFERENCES source_documents(id) ON DELETE SET NULL;
ALTER TABLE manuals ADD COLUMN IF NOT EXISTS category TEXT;

ALTER TABLE manuals ADD COLUMN IF NOT EXISTS categories TEXT[] NOT NULL DEFAULT '{}';
UPDATE manuals SET categories = ARRAY[category] WHERE category IS NOT NULL AND categories = '{}';
ALTER TABLE manuals DROP COLUMN IF EXISTS category;

ALTER TABLE manuals ADD COLUMN IF NOT EXISTS sub_category TEXT;
ALTER TABLE manuals ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE manuals ADD COLUMN IF NOT EXISTS ai_suggested_sub TEXT;

CREATE TABLE IF NOT EXISTS manual_trails (
    id SERIAL PRIMARY KEY,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    created_by TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE(category, name)
);

CREATE TABLE IF NOT EXISTS manual_drafts (
    id SERIAL PRIMARY KEY,
    manual_id INTEGER NOT NULL UNIQUE REFERENCES manuals(id) ON DELETE CASCADE,
    content JSONB NOT NULL DEFAULT '[]',
    edited_by TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- 화면 담당자 원장은 backend_app/sql/screen_owners_kyj.sql을 DBeaver에서
-- 사용자가 직접 실행해 생성·적재한다. 애플리케이션은 DDL을 자동 실행하지 않는다.
